version: '3'

services:
  oracle-19c:
    build:
      context: ./oracle-19c
      dockerfile: Dockerfile
    restart: always
    environment:
      - ORACLE_SID=ORCL
      - ORACLE_PWD=${ORACLE_PASSWORD}
      - TZ=${TIME_ZONE}
    volumes:
      - oracle-19c-data:/opt/oracle/oradata
    ports:
      - 1521:1521
      
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_PASSWORD}
      - TZ=${TIME_ZONE}
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  oracle-19c-data:
  mariadb-data:
