version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - art-pms
    
  art-pms:
    build:
      context: ./art_pms
      dockerfile: Dockerfile
    ports:
      - 8080:8080