version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app-sample
    
  app-sample:
    build:
      context: ./sample
      dockerfile: Dockerfile
    ports:
      - 8080:8080